{{- if .Values.historyServer.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "spark-operator.fullname" . }}-history-server
  namespace: {{ default .Release.Namespace .Values.historyServer.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-history-server
    app.kubernetes.io/instance: {{ include "spark-operator.fullname" . }}-history-server
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  ports:
  - port: 18080
    name: history-server
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}-history-server
    app.kubernetes.io/instance: {{ include "spark-operator.fullname" . }}-history-server
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
{{- end }}
