apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - script: |
      sed \
      -e "s|{{AWS_ACCESS_KEY_ID}}|$AWS_ACCESS_KEY_ID|g" \
      -e "s|{{AWS_SECRET_ACCESS_KEY}}|$AWS_SECRET_ACCESS_KEY|g" \
      -e "s|{{AWS_SESSION_TOKEN}}|$AWS_SESSION_TOKEN|g" \
      -e "s|{{S3_READ_URL}}|s3a://$AWS_BUCKET_NAME/$AWS_BUCKET_PATH/spark-s3-readwrite/README.md|g" \
      -e "s|{{S3_WRITE_URL}}|s3a://$AWS_BUCKET_NAME/$(cat .tmp/s3_bucket_path)|g" \
      templates/spark-s3-readwrite.yaml | kubectl apply -n $NAMESPACE -f -
