apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
# the order is important here
- command: kubectl apply -n hdfs-kerberos -f hdfs-kerberos/configmaps
  timeout: 600
- command: kubectl apply -n hdfs-kerberos -f hdfs-kerberos/volumes
  timeout: 600
- command: kubectl apply -n hdfs-kerberos -f hdfs-kerberos/kerberos-deployment.yaml
  timeout: 600
- command: kubectl wait deployment/kerberos --for=condition=available --timeout=5m -n hdfs-kerberos
  timeout: 600
- command: kubectl apply -n hdfs-kerberos -f hdfs-kerberos/namenode-deployment.yaml
  timeout: 600
- command: kubectl wait deployment/hdfs-namenode --for=condition=available --timeout=5m -n hdfs-kerberos
  timeout: 600
- command: kubectl apply -n hdfs-kerberos -f hdfs-kerberos/datanode-deployment.yaml
  timeout: 600
- command: kubectl wait deployment/hdfs-datanode --for=condition=available --timeout=5m -n hdfs-kerberos
  timeout: 600
