apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-hdfs-test
spec:
  type: Scala
  mode: cluster
  image: SPARK_IMAGE_FULL_NAME
  imagePullPolicy: IfNotPresent
  mainClass: org.apache.spark.examples.HdfsTest
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_SCALA_VERSION-SPARK_VERSION.jar"
  arguments:
  - "hdfs://namenode.hdfs-kerberos.svc.cluster.local:9000/spark/README.txt"
  sparkConf:
    "spark.scheduler.maxRegisteredResourcesWaitingTime": "2400s"
    "spark.scheduler.minRegisteredResourcesRatio": "1.0"
    "spark.kubernetes.submission.connectionTimeout": "60000"
    "spark.kubernetes.submission.requestTimeout": "60000"
  hadoopConfigMap: hadoop-conf
  sparkVersion: SPARK_VERSION
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: "512m"
    labels:
      version: SPARK_VERSION
    serviceAccount: spark-operator-spark
    secrets:
    - name: hadoop-token
      path: /mnt/secrets
      secretType: HadoopDelegationToken
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    deleteOnTermination: false
    labels:
      version: SPARK_VERSION
    secrets:
    - name: hadoop-token
      path: /mnt/secrets
      secretType: HadoopDelegationToken
