apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: shuffle-app
spec:
  type: Scala
  mode: cluster
  image: SPARK_IMAGE_FULL_NAME
  imagePullPolicy: IfNotPresent
  mainClass: ShuffleApp
  mainApplicationFile: "https://kudo-spark.s3-us-west-2.amazonaws.com/spark-scala-tests-3.0.0-20200819.jar"
  arguments:
  - "4"
  - "12000"
  - "100"
  - "4"
  sparkConf:
    "spark.scheduler.maxRegisteredResourcesWaitingTime": "3m"
    "spark.scheduler.minRegisteredResourcesRatio": "1"
    "spark.kubernetes.submission.connectionTimeout": "60000"
    "spark.kubernetes.submission.requestTimeout": "60000"
  sparkVersion: SPARK_VERSION
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: "512m"
    labels:
      version: SPARK_VERSION
    serviceAccount: spark-operator-spark
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    deleteOnTermination: false
    labels:
      version: SPARK_VERSION

