apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: spark-test-rbac
  name: spark-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark
  namespace: spark-test-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-role
subjects:
- kind: ServiceAccount
  name: spark-test-rbac-spark
  namespace: spark-test-rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-test-rbac-spark-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-test-rbac-spark-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spark-test-rbac-spark-operator
subjects:
- kind: ServiceAccount
  name: spark-test-rbac-spark-operator
  namespace: spark-test-rbac
