apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - script: |
      /bin/bash << 'EOF'
        set -x
        ATTEMPT=0
        while true; do
          HELM_STATUS=$(helm list -A -o json | jq '.[] | select(.namespace == "spark-test-rbac") | select(.name == "spark-test-rbac") | .status')

          # Break out if zero results.
          if [[ -z "${HELM_STATUS}" ]]; then
            break
          fi

          # Issue uninstall.
          helm uninstall spark-test-rbac -n spark-rbac-test
          kubectl delete clusterrole spark-test-rbac
          kubectl delete clusterrolebinding spark-test-rbac
          kubectl delete ns spark-rbac-test

          echo "Waiting for previous helm release to terminate. Sleeping and retrying in 10 seconds"
          sleep 10s
          ATTEMPT=$(( ATTEMPT+ 1 ))
          if [ "${ATTEMPT}" -ge 30 ]; then
              echo "Have attempted for 5 mins, exiting"
              exit 1
          fi
        done

        helm repo add spark-operator http://chartmuseum:CHARTMUSEUM_PORT
        helm repo update
        helm install \
        spark-test-rbac \
        spark-operator/spark-operator \
        --create-namespace \
        --namespace spark-test-rbac \
        --debug \
        --set image.repository=OPERATOR_DOCKER_REPO \
        --set image.tag=OPERATOR_VERSION \
        --set historyServer.image.repository=SPARK_DOCKER_REPO \
        --set historyServer.image.tag=SPARK_IMAGE_TAG \
        --set sparkJobNamespace=spark-test-rbac \
        --wait \
        --timeout 600s
      EOF
    timeout: 3600
