apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: mock-task-runner
spec:
  type: Scala
  mode: cluster
  image: SPARK_IMAGE_FULL_NAME
  imagePullPolicy: IfNotPresent
  mainClass: MockTaskRunner
  mainApplicationFile: "https://kudo-spark.s3-us-west-2.amazonaws.com/spark-scala-tests-3.0.0-20200819.jar"
  arguments:
  - "1"
  - "15"
  sparkConf:
    "spark.scheduler.maxRegisteredResourcesWaitingTime": "2400s"
    "spark.scheduler.minRegisteredResourcesRatio": "1.0"
    "spark.kubernetes.submission.connectionTimeout": "60000"
    "spark.kubernetes.submission.requestTimeout": "60000"
    "spark.local.dir": "/opt/spark/work-dir/tmp"
  sparkVersion: SPARK_VERSION
  restartPolicy:
    type: Never
  volumes:
  - name: test-volume
    hostPath:
      path: /data
      type: DirectoryOrCreate
  driver:
    cores: 1
    memory: "512m"
    labels:
      version: SPARK_VERSION
      metrics-exposed: "true"
    serviceAccount: spark-operator-spark
    volumeMounts:
    - name: test-volume
      mountPath: /opt/spark/work-dir
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    deleteOnTermination: false
    labels:
      version: SPARK_VERSION
      metrics-exposed: "true"
    volumeMounts:
    - name: test-volume
      mountPath: /opt/spark/work-dir
