apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - script: |
      for i in `seq 2`
      do
        helm uninstall spark-operator-$i -n spark-namespace-$i
        kubectl delete ns spark-namespace-$i
      done
    timeout: 600