apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 120
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: spark-operator
  name: spark-operator-default-sa-spark
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: spark-operator
  name: spark-operator-default-sa
