apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-s3-readwrite
spec:
  type: Scala
  mode: cluster
  image: SPARK_IMAGE_FULL_NAME
  imagePullPolicy: IfNotPresent
  mainClass: S3Job
  mainApplicationFile: "https://kudo-spark.s3-us-west-2.amazonaws.com/spark-scala-tests-3.0.0-20200819.jar"
  sparkConf:
    "spark.scheduler.maxRegisteredResourcesWaitingTime": "2400s"
    "spark.scheduler.minRegisteredResourcesRatio": "1.0"
    "spark.kubernetes.submission.connectionTimeout": "60000"
    "spark.kubernetes.submission.requestTimeout": "60000"
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.hadoop.fs.s3a.aws.credentials.provider": "org.apache.hadoop.fs.s3a.TemporaryAWSCredentialsProvider"
  sparkVersion: SPARK_VERSION
  arguments:
  - "--readUrl"
  - "{{S3_READ_URL}}"
  - "--writeUrl"
  - "{{S3_WRITE_URL}}"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: "512m"
    labels:
      version: SPARK_VERSION
    serviceAccount: spark-operator-spark
    env:
    env:
    - name: AWS_ACCESS_KEY_ID
      value: "{{AWS_ACCESS_KEY_ID}}"
    - name: AWS_SECRET_ACCESS_KEY
      value: "{{AWS_SECRET_ACCESS_KEY}}"
    - name: AWS_SESSION_TOKEN
      value: "{{AWS_SESSION_TOKEN}}"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    deleteOnTermination: false
    labels:
      version: SPARK_VERSION
